# Файл: .golangci.yml
run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata

linters:
  enable:
    - gofmt
    - govet
    - revive
    - errcheck
    - staticcheck
    - gosimple
    - gosec
    - ineffassign
    - unconvert
    - gocyclo
    - dupl
    - misspell
    - unparam
    - dogsled
    - nakedret
    - exportloopref
    - bodyclose
    - gochecknoinits
    - stylecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec